version: '3'
services:  
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432" 
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=doggr
      - POSTGRES_PASSWORD=doggr
      - POSTGRES_DB=doggr
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U doggr"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: backend
    build: ./backend/
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=doggr
      - DB_USER=doggr
      - DB_PASS=doggr
      - HOST=0.0.0.0
      - PORT=8080
      - FB_API_KEY=AIzaSyBUJFXnbeZ4e01yv5IDSpGkViGw7TKQI48
      - FB_AUTH_DOMAIN=npsee-a9647.firebaseapp.com
      - FB_PROJ_ID=npsee-a9647
      - FB_STORAGE_BUCKET=npsee-a9647.appspot.com
      - FB_MESSAGING_SENDER_ID=449508238502
      - FB_APP_ID=1:449508238502:web:dbda8ae57f1b0e227b4067
      - FB_MEASUREMENT_ID=G-GS17ZR9KRG
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    container_name: frontend
    build: ./frontend/
    restart: always
    ports:
      - "5173:5173"
    environment:
      - API_HOST=localhost
      - PORT=8080
      - FB_API_KEY=AIzaSyBUJFXnbeZ4e01yv5IDSpGkViGw7TKQI48
      - FB_AUTH_DOMAIN=npsee-a9647.firebaseapp.com
      - FB_PROJ_ID=npsee-a9647
      - FB_STORAGE_BUCKET=npsee-a9647.appspot.com
      - FB_MESSAGING_SENDER_ID=449508238502
      - FB_APP_ID=1:449508238502:web:dbda8ae57f1b0e227b4067
      - FB_MEASUREMENT_ID=G-GS17ZR9KRG
    depends_on:
      - backend

  microservice:
    container_name: microservice
    build: ./microservice/
    restart: always
    ports:
      - "5144:80"

volumes:
  db:
    driver: local
